name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: MagTemTenebrius/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Yekaterinburg
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 7
          plugin_languages_analysis_timeout: 15
          plugin_stars: yes
          config_order: base.header, isocalendar, languages, stars
